### ISSUE TITLE
fix/브랜치 네이밍 변경 필요성

### ISSUE THREAD

**Issue by songhaechan** [AmorGakCo/Backend#73]
## 오류 설명
기존 feat/#00 는 이슈 번호를 따라가면 이슈 내용을 볼 수 있긴 하지만
브랜치 네임만으로 어떤 기능을 담당하는 브랜치인지 알기가 어렵습니다.
## 원하는 방향
feat/#00-기능명 좀 더 명확하게 브랜치의 목적을 표현하는게 좋을 것 같다고 생각됩니다.

**Comment by ohksj77** [comment]
좋은 의견입니다! 앞으로 수정된 브랜치 네이밍 사용해봅시다.
